Welcome to the website, <?php echo $user['User']['username']; ?>!

*Your User Information*

Username: <?php echo $user['User']['username']."\n"; ?>
Password: <?php echo $password; ?>


You can now log in into your new account at: <?php echo Router::url(array('plugin' => 'auth', 'controller' => 'users', 'action' => 'login'), true)."\n"; ?>
Remember you can change this autogenerated password to something more memorable anytime.


Greetings,
Support